# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='shortCode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
